#!/bin/sh
# Regenerates RelayPulse/Net/AgentSource.swift from the desktop repo's agent.py.
# The phone runs that same collect() over SSH on servers without the agent, so
# both apps read a server identically. Run after every agent.py change.
set -e
SRC="${1:-$HOME/Desktop/RelayPulse-src/agent/agent.py}"
cd "$(dirname "$0")/.."
python3 -m py_compile "$SRC"
B64=$(base64 < "$SRC" | tr -d '\n')
SUM=$(shasum -a 256 "$SRC" | cut -c1-12)
cat > RelayPulse/Net/AgentSource.swift <<SWIFT
// GENERATED by tools/embed-agent.sh from RelayPulse-src/agent/agent.py
// (sha256 $SUM). Do not edit by hand — rerun the script.
enum AgentSource {
    static let sha256Prefix = "$SUM"
    static let base64 = "$B64"
}
SWIFT
echo "AgentSource.swift <- $SRC ($SUM, $(wc -c < "$SRC" | tr -d ' ') bytes)"
